create table CUSTOMER_ADDRESS (
    CUSTOMER_ID INT,
    ADDRESS_ID INT,
    CONSTRAINT FK_CUSTOMER
      FOREIGN KEY(CUSTOMER_ID)
      REFERENCES CUSTOMER(CUSTOMER_ID),
    CONSTRAINT FK_ADDRESS
      FOREIGN KEY(ADDRESS_ID)
      REFERENCES ADDRESS(ADDRESS_ID)
 )