create table REQUEST_CUSTOMER (
    CUSTOMER_ID INT,
    REQUEST_ID INT,
    CONSTRAINT FK_CUSTOMER
      FOREIGN KEY(CUSTOMER_ID)
      REFERENCES CUSTOMER(CUSTOMER_ID),
    CONSTRAINT FK_REQUEST
      FOREIGN KEY(REQUEST_ID)
      REFERENCES REQUEST(REQUEST_ID)
 )