create table RESQUEST_ADDRESS (
    REQUEST_ID INT,
    ADDRESS_ID INT,
    CONSTRAINT FK_CUSTOMER
      FOREIGN KEY(REQUEST_ID)
      REFERENCES REQUEST(REQUEST_ID),
    CONSTRAINT FK_ADDRESS
      FOREIGN KEY(ADDRESS_ID)
      REFERENCES ADDRESS(ADDRESS_ID)
 )